# fly.toml app configuration file generated for cimd-service on 2025-10-26T05:38:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cimd-service'
primary_region = 'iad'

[env]
  PORT = "3000"
  DB_PATH="/data/db.sqlite"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[mounts]]
source = "data"
destination = "/data"
auto_extend_size_threshold = 80
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"
processes = ["app"]

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
